### ISSUE TITLE
resource_reference_without_whitespace error on resource collection

### ISSUE THREAD

**Issue by rendhalver** [voxpupuli/puppet-lint-resource_reference_syntax#9] opened 2016-08-09 19:44 UTC
For some reason I am getting an error from your module where I don't think there should be one.

Error message:
resource_reference_without_whitespace:ERROR:whitespace between reference type and title

Resource.
Sshkeys::Set_authorized_key <<| tag == $::facts[fqdn] |>>

I am rather sure that is a valid resource collector.
If I use a non structured fact it fails.
If I take out all the spaces on that line it passes.

Whereas this resource collector does not produce the error.
Sshkey <<| tag == $primary_server |>>

Is something going wrong because it is a sub resource?

**Comment by domcleal** [comment] 2016-08-10 07:42
I can't reproduce this:

<pre>
$ cat test.pp
Sshkeys::Set_authorized_key <<| tag == $::facts[fqdn] |>>
$ puppet-lint test.pp
$
</pre>

and these tests all pass: https://github.com/domcleal/puppet-lint-resource_reference_syntax/commit/8f6100ff5226e81100f0286d333819f7f4001736.  Are you on version 1.0.8?

**Comment by rendhalver** [comment] 2016-08-10 12:41
My Gemfile.lock file says I am actually on 1.0.9 which I though was weird.
I am still on puppet-lint 1.1.0. Would that have any effect?

**Comment by rendhalver** [comment] 2016-08-10 12:44
I am also using puppet 4.4.2 if that changes anything.

**Comment by domcleal** [comment] 2016-08-10 12:47
Does the example I gave also pass for you? If so, please adjust or re-check the original.

**Comment by rendhalver** [comment] 2016-08-10 12:53
Yes it does pass in my local environment.
We use Jenkins to run our tests.
I will see if the same code passes on our test server.
I will try and work out what is going on and get back to you.

**Comment by rendhalver** [comment] 2016-08-10 12:53
Oh and thanks for the quick response. :)

**Comment by tuxmea** [comment] 2016-08-10 16:45
Hi Pete,

this was an issue with an older version.
Please check whether your testing server has an old version cached.

Best,
Martin

**Comment by tuxmea** [comment] 2016-11-23 10:16
@rendhalver is this issue still open or can we close this?

**Comment by tuxmea** [comment] 2016-12-06 09:57
No feedback. closing.

**Comment by rendhalver** [comment] 2016-12-06 13:37
Sorry for late reply.
Yes it still happening.
Would the version of puppet-lint have any bearing on this?
We are locked at 1.1.0 because of the plugins we use.

**Comment by tuxmea** [comment] 2016-12-07 09:33
If you are stuck with puppet-lint 1.1.0 you can open issues at the plugins which have not yet updated to the newest version of puppet-lint.
(btw: which ones are these that force you to 1.1.0?)

**Comment by rendhalver** [comment] 2016-12-07 14:17
Quite a few it seems.
Excerpt from my Gemfie.lock:

    puppet-lint (1.1.0)
    puppet-lint-absolute_classname-check (0.1.3)
      puppet-lint (~> 1.0)
    puppet-lint-empty_string-check (0.2.1)
      puppet-lint (~> 1.0)
    puppet-lint-file_ensure-check (0.3.1)
      puppet-lint (>= 1.0, < 3.0)
    puppet-lint-leading_zero-check (0.1.0)
      puppet-lint (~> 1.0)
    puppet-lint-resource_reference_syntax (1.0.9)
      puppet-lint (>= 1.0, < 3.0)
    puppet-lint-roles_and_profiles-check (0.1.0)
      puppet-lint (~> 1.0)
    puppet-lint-spaceship_operator_without_tag-check (0.1.0)
      puppet-lint (~> 1.0)
    puppet-lint-strict_indent-check (2.0.1)
      puppet-lint (~> 1.0)
    puppet-lint-trailing_comma-check (0.3.2)
      puppet-lint (>= 1.0, < 3.0)
    puppet-lint-trailing_newline-check (1.0.0)
      puppet-lint (~> 1.0)
    puppet-lint-undef_in_function-check (0.1.0)
      puppet-lint (~> 1.0)
    puppet-lint-unquoted_string-check (0.2.5)
      puppet-lint (~> 1.0)
    puppet-lint-variable_contains_upcase (1.0.0)
      puppet-lint (~> 1.0)

**Comment by tuxmea** [comment] 2016-12-08 11:11
puppet-lint (1.1.0)
puppet-lint-absolute_classname-check (0.1.3)
  puppet-lint (~> 1.0)
Fixed upstream: https://github.com/voxpupuli/puppet-lint-absolute_classname-check in version 0.2.4

puppet-lint-empty_string-check (0.2.1)
  puppet-lint (~> 1.0)
Fixed upstream: https://github.com/voxpupuli/puppet-lint-empty_string-check in version 0.2.2

puppet-lint-file_ensure-check (0.3.1)
  puppet-lint (>= 1.0, < 3.0)
Safe.

puppet-lint-leading_zero-check (0.1.0)
  puppet-lint (~> 1.0)
Fixed upstream: https://github.com/voxpupuli/puppet-lint-leading_zero-check in version 0.1.1

puppet-lint-resource_reference_syntax (1.0.9)
  puppet-lint (>= 1.0, < 3.0)
Safe.

puppet-lint-roles_and_profiles-check (0.1.0)
  puppet-lint (~> 1.0)
Fixed upstream: https://github.com/mcanevet/puppet-lint-roles_and_profiles-check in version 0.1.1

puppet-lint-spaceship_operator_without_tag-check (0.1.0)
  puppet-lint (~> 1.0)
Fixed upstream: https://github.com/voxpupuli/puppet-lint-spaceship_operator_without_tag-check in version 0.1.1

puppet-lint-strict_indent-check (2.0.1)
  puppet-lint (~> 1.0)
PR created: https://github.com/relud/puppet-lint-strict_indent-check/pull/8

puppet-lint-trailing_comma-check (0.3.2)
  puppet-lint (>= 1.0, < 3.0)
Safe.

puppet-lint-trailing_newline-check (1.0.0)
  puppet-lint (~> 1.0)
PR created: https://github.com/rodjek/puppet-lint-trailing_newline-check/pull/3

puppet-lint-undef_in_function-check (0.1.0)
  puppet-lint (~> 1.0)
Fixed upstream: https://github.com/voxpupuli/puppet-lint-undef_in_function-check in version 0.2.1

puppet-lint-unquoted_string-check (0.2.5)
  puppet-lint (~> 1.0)
Fixed upstream: https://github.com/voxpupuli/puppet-lint-unquoted_string-check in version 0.3.0

puppet-lint-variable_contains_upcase (1.0.0)
  puppet-lint (~> 1.0)
Fixed upstream: https://github.com/fiddyspence/puppetlint-variablecase in version 1.0.2

**Comment by rendhalver** [comment] 2016-12-08 14:20
Thanks.
I have been way too busy to check if newer releases happened.
I will get those updated and let you know how it goes.

**Comment by rendhalver** [comment] 2016-12-08 20:52
Thank you!
I just tested those updates including your two new PR's and all my tests work as expected.

It will be nice to finally upgrade to puppet-lint 2! <3

**Closed** 2017-12-30 15:42 UTC
